### PR TITLE
Added some pictures to the README 

### PR DESCRIPTION
**Pull request by MangoIV**
Hi! Someone from a server I'm on complained about Repos not having pictures in their readme, so here we go, I'm doing my part. :)

(cool board by the way)

### CODE REVIEW

**Comment by crides** [comment]
I expected the list to be long, so all board pics are in versions.md, and I hope the link to that is obvious enough. If people find it not to be the case, is there something you would suggest?

**Comment by MangoIV** [comment]
Well, of course it's your decision but I think there are so many keyboards out there, sometimes you just don't wanna take the time and go through all the files in the repo to find how it looks. 
I also always just put the pics at the end of the README so they're reasonably easy to find and still don't take up the space of the more important info ;)

**Comment by crides** [comment]
I certainly don't expect people to go through all the files, that's why it's linked in the README, and I was asking if there's anything that could be done to make the link more obvious

Alternatively, I could just put the picture of the latest version at the end of the README.

**Comment by MangoIV** [comment]
I think the latter is a good compromise. Sorry, that probably took more of the time of you than it should have :D

**Comment by crides** [comment]
No problem. I need other people to criticize my work :).

Also the latest is v3.2. I have a habit of not documenting things until after I switched to a new version

**Pull request closed without merging**
